<!-- Report detail page -->
<script lang="ts">
	import { enhance } from '$app/forms';
	import { marked } from 'marked';
	import type { PageData } from './$types';

	export let data: PageData;

	// Function to render markdown to HTML
	function renderMarkdown(content: string) {
		return marked.parse(content);
	}
</script>

<div class="container mx-auto max-w-screen-lg px-4 py-8">
	<div class="mb-8">
		<a href="/" class="text-blue-600 hover:text-blue-800">← Back to Reports</a>
	</div>

	{#if data.report}
		<div class="rounded-lg bg-white p-6 shadow-lg">
			<h1 class="mb-4 text-3xl font-bold">{data.report.topic}</h1>
			<p class="mb-6 text-gray-600">{data.report.description}</p>

			<div class="mb-6 flex items-center justify-between">
				<span
					class="inline-flex items-center rounded-full px-3 py-1 text-sm
          {data.report.status === 'completed'
						? 'bg-green-100 text-green-800'
						: data.report.status === 'pending'
							? 'bg-yellow-100 text-yellow-800'
							: data.report.status === 'error'
								? 'bg-red-100 text-red-800'
								: 'bg-gray-100 text-gray-800'}"
				>
					{data.report.status}
				</span>

				{#if data.report.status === 'pending' && !data.isProcessing}
					<form method="POST" action="?/startResearch" use:enhance>
						<button
							type="submit"
							class="rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
						>
							Start Research
						</button>
					</form>
				{:else if data.isProcessing}
					<span class="text-blue-600">Research in progress...</span>
				{/if}
			</div>

			{#if data.report.content}
				<div class="prose prose-lg max-w-screen-lg mx-auto">
					<!-- 
						Content is sanitized server-side before being stored in the database.
						The content is generated by our own system and not user-provided.
						We render the markdown content to HTML
					-->
					{@html renderMarkdown(data.report.content)}
				</div>
			{:else if data.report.status === 'pending'}
				<div class="py-8 text-center">
					<div
						class="mx-auto mb-4 h-12 w-12 animate-spin rounded-full border-b-2 border-blue-600"
					></div>
					<p class="text-gray-600">Waiting to start research...</p>
				</div>
			{:else}
				<p class="text-gray-600">No content available.</p>
			{/if}

			<div class="mt-6 text-sm text-gray-500">
				Created: {new Date(data.report.created_at).toLocaleString()}
				<br />
				Last updated: {new Date(data.report.updated_at).toLocaleString()}
			</div>
		</div>
	{:else}
		<div class="rounded-lg bg-red-50 p-4 text-red-800">Report not found.</div>
	{/if}
</div>
